### ISSUE TITLE
Failed to execute goal com.github.s4u.plugins:pgpverify-maven-plugin

### ISSUE THREAD

**Issue by adminrezo** [apereo/cas-services-management-overlay#14]
Hi,

I have git pulled cas-services-management-overlay.
When building cas-services-management-overlay, build is failing with this error :

    ...
    [INFO] --- pgpverify-maven-plugin:1.1.0:check (default) @ cas-overlay ---
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 02:08 min (Wall Clock)
    [INFO] Finished at: 2017-02-24T13:05:33+01:00
    [INFO] Final Memory: 13M/106M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal com.github.s4u.plugins:pgpverify-maven-plugin:1.1.0:check (default) on project cas-overlay: Connexion terminée par expiration du délai d'attente (Connection timed out) -> [Help 1]
    ...

My config : Debian stretch, Openjdk-8-jre
JAVA_HOME : /usr/lib/jvm/java-8-openjdk-amd64/jre/

Thanks in advance for your help.

**Comment by mmoayyed** [comment]
Fix your connection please so it doesn't time out.

**Comment by daniel-widrick** [comment]
I have a similar issue. Get a no route to host error. Is the build doing something on a non-standard port (eg not 80 or 443) somewhere?
