### ISSUE TITLE
Character not allowed on service name

### ISSUE THREAD

**Issue by titansmc** [apereo/cas-services-management-overlay#5]
Hi ,
I was trying to add a service named "Observium/Nagios"

 And it gave me an error, "An error has occurred while attempting to
 save br/>the service. Please try again later.""

 When I went to look into the logs, I found it was trying to create

 /etc/cas/services/Observium/Nagios-5084896551456820.json

 So I guess when you try to create a service name containing "/" it
 br/>should say ""you are not allow to use this symbol. Am I right?

 Using CAS 4.1 

Cheers

**Comment by mmoayyed** [comment]
Yes you are perfectly right
