### ISSUE TITLE
Broken link to Ajax Ng-table library

### ISSUE THREAD

**Issue by mtiadm** [apereo/cas-services-management-overlay#7]
The script and css locations defined for ng-tables are broken, the rawgit links popup 404 error and the interface is unusable : 

cdn.rawgit.com/esvit/ng-table/master/dist/ng-table.min.css
cdn.rawgit.com/esvit/ng-table/master/dist/ng-table.min.js

Please update the default template to point to cloudflare :

cdnjs.cloudflare.com/ajax/libs/ng-table/1.0.0/ng-table.min.css
cdnjs.cloudflare.com/ajax/libs/ng-table/1.0.0/ng-table.js

**Comment by mmoayyed** [comment]
Please submit a pull request to update the default template to point to cloudflare. Thanks!

**Comment by dannymk** [comment]
I was able to get the service management webapp finally configured to let me in when I ran into this issue :-(
Any status on an update to the overlay project?

**Comment by mmoayyed** [comment]
This is fixed in 5.0.2

**Comment by dannymk** [comment]
That may be but the version in this overlay is 5.0.1 and this is the repo that is referenced in the documentation.

**Comment by mmoayyed** [comment]
And 5.0.2 is released the versions will change.

**Comment by dannymk** [comment]
OK, good to know.  Thank you.
